import {Type} from '@sinclair/typebox';

const UpdateDeviceRequest = Type.Object({
  camName: Type.Optional(Type.String()),
  ipAddress: Type.Optional(Type.String()),
  username: Type.Optional(Type.String()),
  password: Type.Optional(Type.String()),
  protocol: Type.Optional(Type.String()),
  rtspPath: Type.Optional(Type.String()),
  substreamPath: Type.Optional(Type.String()),
  rtspPort: Type.Optional(Type.Integer()),
  preferTcp: Type.Optional(Type.Boolean()),
  substreamMode: Type.Optional(Type.Boolean()),
  mjpegPath: Type.Optional(Type.String()),
  mjpegPort: Type.Optional(Type.Number()),
  onvifPort: Type.Optional(Type.Number()),
  audioEnabled: Type.Optional(Type.Boolean()),
  audioVolume: Type.Optional(Type.Integer()),
  brightness: Type.Optional(Type.Integer()),
  bufferPostrecording: Type.Optional(Type.Integer()),
  channel: Type.Optional(Type.Integer()),
  contrast: Type.Optional(Type.Integer()),
  disabled: Type.Optional(Type.Boolean()),
  frameDownscaleFactor: Type.Optional(Type.Number()),
  hlsSegmentDuration: Type.Optional(Type.Number()),
  hlsSegmentSize: Type.Optional(Type.Integer()),
  hlsWindowSize: Type.Optional(Type.Integer()),
  invert: Type.Optional(Type.Boolean()),
  maxMotionArea: Type.Optional(Type.Integer()),
  maxMotionFrames: Type.Optional(Type.Integer()),
  minMotionFrames: Type.Optional(Type.Integer()),
  motionAlgorithm: Type.Optional(Type.Boolean()),
  motionAnalysisPercentage: Type.Optional(Type.Integer()),
  motionAnalysisSswLength: Type.Optional(Type.Integer()),
  motionBlendRatio: Type.Optional(Type.Integer()),
  motionDebug: Type.Optional(Type.Boolean()),
  // motionMap: Type.Optional(Type.String()), //TODO: Add support for Schedule
  onvifEventsEnabled: Type.Optional(Type.Boolean()),
  saturation: Type.Optional(Type.Integer()),
  // schedule: Type.Optional(Type.String()), //TODO: Add support for Schedule
  scheduleOverrideGlobal: Type.Optional(Type.Boolean()),
  signalType: Type.Optional(Type.String()),
  videoInterval: Type.Optional(Type.Integer()),
  videoQuality: Type.Optional(Type.Integer()),
});

export {UpdateDeviceRequest};
